/*
 * generated by Xtext 2.12.0
 */
package gameOfLife.validation

import org.eclipse.xtext.validation.Check
import gameOfLife.dSL.GridPoint
import gameOfLife.dSL.DSLPackage$Literals;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DSLValidator extends AbstractDSLValidator {
	
	@Check
	def checkTImeUnit(GridPoint point){
		if (point !== null){
			if (point.x < 0){
				error("Point coordinates must be greater or equal than zero", Literals.GRID_POINT__X);
			}
			if (point.y < 0){
				error("Point coordinates must be greater or equal than zero", Literals.GRID_POINT__Y);
			}
		}
	}
	
}
