/**
 * generated by Xtext 2.12.0
 */
package persons.tasks.ide;

import persons.tasks.ide.AbstractTaskDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TaskDSLIdeModule extends AbstractTaskDSLIdeModule {
}
