grammar gameOfLife.DSL with org.eclipse.xtext.common.Terminals

generate dSL "http://www.DSL.gameOfLife"

GameSpec: 'GameSpec:'
	'initiallyAlive:' initiallyAlive += GridPoint+
	'bornsIf:' birthRules += Condition+
	'survivesIf:' survivalRules += Condition+
;
	
GridPoint: 
	'(' x = INT
	',' y = INT
	')'
;

Condition: {Condition}
	'('
	(value = INT 'neighbors' relativity = Relativity? | 'none')
	')'
;

Relativity: 
	op = Operator
;

enum Operator:
	GE = 'or more' |
	LE = 'or less' 
;
	

