/*
 * generated by Xtext 2.12.0
 */
package gameOfLife


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DSLStandaloneSetup extends DSLStandaloneSetupGenerated {

	def static void doSetup() {
		new DSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
