/*
 * generated by Xtext 2.12.0
 */
package mars.rover


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MissionsDSLStandaloneSetup extends MissionsDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MissionsDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
