/*
 * generated by Xtext 2.12.0
 */
package persons.tasks.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import persons.tasks.ui.internal.TasksActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TaskDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TasksActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TasksActivator.getInstance().getInjector(TasksActivator.PERSONS_TASKS_TASKDSL);
	}
	
}
